spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mydatabase"
    username: myuser
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
jwt:
  key: "-2988-864584-37-83-1201148-744188-12-120-1082818104181-45-118-10532-3-4179-82516290"